[[plugins]]
repo='vim-airline/vim-airline'
hook_add='''
  let g:airline_theme='gruvbox'
  let g:airline#extensions#tabline#enabled=1
  let g:airline_powerline_fonts=1
'''

[[plugins]]
repo='vim-airline/vim-airline-themes'

[[plugins]]
repo='morhetz/gruvbox'

[[plugins]]
repo='lambdalisue/fern.vim'
hook_add='''
  nnoremap <silent> <C-n> :<C-u>Fern . -drawer<CR>
  nnoremap <silent> <C-N> :<C-u>Fern . -drawer -reveal=%<CR>
'''

[[plugins]]
repo='lambdalisue/fern-git-status.vim'

[[plugins]]
repo='lambdalisue/nerdfont.vim'

[[plugins]]
repo='lambdalisue/fern-renderer-nerdfont.vim'
hook_add='''
  let g:fern#renderer = 'nerdfont'
'''

[[plugins]]
repo='lambdalisue/glyph-palette.vim'
hook_add='''
  augroup my-glyph-palette
    autocmd! *
    autocmd FileType fern call glyph_palette#apply()
    autocmd FileType nerdtree, startify call glyph_palette#apply()
  augroup END
'''

[[plugins]]
repo='airblade/vim-gitgutter'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo='yuki-yano/fuzzy-motion.vim'
hook_add='''
  nmap <Leader>s :<C-u>FuzzyMotion<CR>
'''
[[plugins]]
repo='simeji/winresizer'

[[plugins]]
repo='neoclide/coc.nvim'
rev = 'release'
build='''
  git checkout release
'''
hook_add='''
  inoremap <silent><expr> <TAB>
    \ pumvisible() ? "\<C-n>" :
    \ <SID>check_back_space() ? "\<TAB>" :
    \ coc#refresh()
  inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"
  inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
  function! s:check_back_space() abort
    let col = col('.') - 1
    return !col || getlin('.')[col - 1] =~# '\s'
  endfunction
  nmap <silent> gd <Plug>(coc-definition)
  nmap <silent> gy <Plug>(coc-type-definition)
  nmap <silent> gi <Plug>(coc-implementation)
  nmap <silent> gr <Plug>(coc-references)
'''

[[plugins]]
repo='junegunn/fzf'
build='''
  ./install --all
'''

[[plugins]]
repo='jdkanani/vim-material-theme'
hook_add='''
  colorscheme material-theme
  highlight Normal ctermbg=NONE guibg=NONE
  highlight NonText ctermbg=NONE guibg=NONE
  highlight SpecialKey ctermbg=NONE guibg=NONE
  highlight EndOfBuffer ctermbg=NONE guibg=NONE
'''

[[plugins]]
repo='andweeb/presence.nvim'
hook_add = '''
  let g:presence_auto_update=1
  let g:presence_editing_text = "Editing %s"
  let g:presence_file_explorer_text = "File browsing"
  let g:presence_neovim_image_text = "お前も\nVimmerにならないか？"
'''

[[plugins]]
repo='twitvim/twitvim'
hook_add='''
  let twitvim_browser_cmd = "firefox"
  let twitvim_force_ssl = 1
  let twitvim_count = 40
'''

[[plugins]]
repo='dart-lang/dart-vim-plugin'

[[plugins]]
repo='thosakwe/vim-flutter'

[[plugins]]
repo='tpope/vim-fugitive'

[[plugins]]
repo='othree/html.vim'

[[plugins]]
repo='pangloss/vim-javascript'

[[plugins]]
repo='evanleck/vim-svelte'

[[plugins]]
repo='nvim-treesitter/nvim-treesitter'
merged=0

[[plugins]]
repo='vim-denops/denops.vim'

[[plugins]]
repo='lambdalisue/gina.vim'
